### ISSUE TITLE
dashbase_server.info: NPE at rapid.e.b.b.b(b.java)

### ISSUE THREAD

**Issue by ZongqiangZhang** [dashbase/dashbase-engine-web#330]
A NPE error in dashbase server log as follows, I am not sure if it's expected

INFO 2017-01-22 04:54:19,795 [rapid.util.NumberedFileSet$Watcher:/data/dashbase/data/index1/dashbase_p0/store] (?:?): loaded segment 58843ac3
INFO 2017-01-22 04:54:31,997 [Thread-10] (?:?): deleted segment 587b0083
ERROR 2017-01-22 04:54:34,026 [qtp1650169692-127] (?:?): Exception in query flow
java.lang.NullPointerException
        at rapid.e.b.b.b(b.java)
        at rapid.e.a.b.query(b.java)
        at io.dashbase.http.DashbaseHttpService.lambda$start$5(DashbaseHttpService.java:115)
        at spark.RouteImpl$1.handle(RouteImpl.java:61)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
INFO 2017-01-22 04:55:06,983 [indexer] (?:?): created segment stats file

**Comment by javasoze** [comment]
@ZongqiangZhang Thanks for reporting this, how often does this happen?
